version: '3.8'

services:
  zookeeper:
    image: apache/kafka:3.7.0
    container_name: zookeeper
    command: ["/opt/kafka/bin/zookeeper-server-start.sh", "/opt/kafka/config/zookeeper.properties"]
    ports:
      - "2181:2181"
    environment:
      KAFKA_OPTS: "-Djava.net.preferIPv4Stack=true"

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    command: ["/opt/kafka/bin/kafka-server-start.sh", "/opt/kafka/config/server.properties"]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    volumes:
      - ../conf/kafka/server.properties:/opt/kafka/config/server.properties
    links:
      - zookeeper
  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    ports:
      - "8081:8081"

  wso2mi:
    build:
      context: ../wso2MI  # Path to the directory containing the Dockerfile
    environment:
      - JAVA_OPTS=${JAVA_OPTS}
    ports:
      - "8290:8290"
      - "8253:8253"
      - "5005:5005"
      - "9164:9164"
    volumes:
      - ../conf/MI/deployment.toml:/home/wso2carbon/wso2-config-volume/conf/deployment.toml
      - ../conf/MI/log4j2.properties:/home/wso2carbon/wso2-config-volume/conf/og4j2.properties
      - ../resources/MI/carbonapps:/home/wso2carbon/wso2mi-4.2.0/repository/deployment/server/carbonapps/
      - ../resources/MI/dropins:/home/wso2carbon/wso2mi-4.2.0/dropins
      - ../resources/MI/lib:/home/wso2carbon/wso2mi-4.2.0/lib
    links:
      - zookeeper
      - kafka
      - schema-registry
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://schema-registry:8081/
    depends_on:
      - kafka
      - schema-registry
    links:
      - zookeeper
      - kafka
      - schema-registry
